### ISSUE TITLE
Update HMDB linksets?

### ISSUE THREAD

**Issue by stain** [openphacts/IdentityMappingService#30]
the [HMDB linksets used in 1.5](http://data.openphacts.org/1.5/ims/linksets/HMDB/) are from 2013 using HMDB 3.0, while latest [HMDB is 3.6](http://www.hmdb.ca/downloads).

This includes links to KEGG and Pubchem, in addition to WikiPathways. 

I think @egonw said he could update these:

>  2015-08-07 Egon to create HMDB linksets during week of 24 August

Do we need these updated linksets for the Open PHACTS 2.0 release?

@egonw  - do we have the script that made these linksets somewhere? (the void does not say `pav:createdWith`)

**Comment by egonw** [comment]
Ummm... where did they updated link sets go??

(/me is checking his emails where (if) he sent the new 3.6-based link sets...)

**Comment by egonw** [comment]
OK, see my email, but the script is here anyway: https://github.com/egonw/create-bridgedb-hmdb/blob/master/hmdb2linkset.groovy

**Comment by egonw** [comment]
OK, new files: http://egonw.github.io/create-bridgedb-hmdb/hmdb/3.6.0/hmdb_ls.void.ttl

**Comment by stain** [comment]
Closed: loaded on http://ops2.few.vu.nl/QueryExpander/
